version: 2
project_name: dotfiles

builds:
  - id: dotfiles
    main: ./cmd/dotfiles
    binary: dotfiles
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/ale/dotfiles/internal/version.Version={{.Version}}
      - -X github.com/ale/dotfiles/internal/version.Commit={{.Commit}}
      - -X github.com/ale/dotfiles/internal/version.Date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
